### ISSUE TITLE
workshop pre-list

### ISSUE THREAD

**Issue by gaurav1780** [gaurav1780/comp125practicePackagesV2#2]
Hye Dung,

in file `ListPracticalTest.java`, can you please change all 

```java
assertTrue(methodCall() == n);
```

to 

```java
assertNotNull(methodCall());
assertTrue((Integer)n, methodCall());
```

and,

```java
assertTrue(methodCall() == null);
```

to

```java
assertNull(methodCall());
```

thanks
gaurav

**Comment by RichardVu1711** [comment]
I changed all of them.
Just one question, I think 

 `assertTrue((Integer)n, methodCall());` 
should be:
`assertEquals((Integer)n, methodCall());`

isn't it?

**Comment by gaurav1780** [comment]
yes, my bad. i'll fix it :) thanks!
G
